---
- name: Install deps
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - software-properties-common

- name: Create keyring dir
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Import Grafana GPG key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    keyring: /etc/apt/keyrings/grafana.gpg
    state: present

- name: Add grafana stable repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main

- name: Install Grafana OSS
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true
  notify: restart grafana

- name: Create service override dir
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/grafana-server.service.d
    mode: '0755'

- name: Add service override.conf
  ansible.builtin.template:
    src: grafana-override.conf
    dest: /etc/systemd/system/grafana-server.service.d/override.conf
    mode: '0644'
  notify: restart grafana

- name: Copy grafana.ini
  ansible.builtin.template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    mode: '0640'
  notify: restart grafana

- name: Restore grafana.db
  ansible.builtin.copy:
    src: grafana.db
    dest: /var/lib/grafana/grafana.db
    mode: '0640'
    owner: grafana
    group: grafana
  notify: restart grafana
